version: "3.1"
services:
  api:
    #? Set container and image name
    container_name: animus_api
    image: saptaktdk123/animus:1.0.7

    #? Environment
    environment:
      MONGO_CONN_URL: "mongodb://animus_admin:testing123@animus_db:27017/animus_db?authSource=admin"

    #? Ports
    ports:
      - 8080:8080

    depends_on:
      - db

  db:
    #? Set container name
    container_name: animus_db
    image: mongo:6

    #? Restart if down
    restart: always

    #? Environment
    environment:
      MONGO_INITDB_ROOT_USERNAME : "animus_admin"
      MONGO_INITDB_ROOT_PASSWORD : "testing123"
      MONGO_INITDB_DATABASE : "animus_db"

    #? Ports
    ports:
      - 27017:27017
