name: Build and Push Animus Service

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v3.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean
        run: mvn -B clean -DskipTests -DBUILD_NUMBER=${{ github.run_number }}

      - name: Build
        run: mvn -B package -DskipTests -DBUILD_NUMBER=${{ github.run_number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v4
        with:
            context: .
            file: Dockerfile
            platforms: linux/amd64
            push: true
            tags: ${{ secrets.DOCKERHUB_PASSWORD }}/animus:1.0.${{ github.run_number }}